numbers = [5, 1, 3, 7, 2]
numbers.append(9)
print(numbers)
numbers.insert(1,10)
print(numbers)
numbers.remove(5)
print(numbers)
numbers.clear()
numbers = [5, 1, 3, 7, 2]
print(numbers)
numbers.pop()
print(numbers)
numbers = [5, 1, 2, 3, 7, 2]
print(numbers.index(5))
print(3 in numbers)
print(numbers.count(2))
numbers.sort()
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
print(numbers2)